DROP TABLE IF EXISTS staff_memberships CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS shop_addresses CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
DROP TYPE IF EXISTS shop_approval_status CASCADE;
