DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS product_stock_history CASCADE;
DROP TABLE IF EXISTS product_performance CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TYPE IF EXISTS product_status CASCADE;
